apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_kubernetes_io_config_mirror]
            action: drop
            regex: true
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: .+
          - source_labels: [__meta_kubernetes_pod_uid]
            target_label: __tmp_pod_uid
            action: replace
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
            action: replace
          - source_labels: [__meta_kubernetes_pod_namespace]
            target_label: namespace
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
            action: replace
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
            action: replace